- name: Send notify to Telegram
  hosts: all
  gather_facts: true

  tasks:
    - name: Send notify to Patient
      community.general.telegram:
        token: "{{ lookup('env','TELEGRAM_TOKEN') }}"
        api_args:
          chat_id: "{{ lookup('env','TELEGRAM_CHAT_ID') }}"
          parse_mode: "markdown"
          text: "The patient has not opened the fridge for a day"
          disable_web_page_preview: true
          disable_notification: true
