---
- name: Send notify to Telegram
  community.general.telegram:
    token: '5915517965:AAFgYY9P0Ox5w3DvrJrC16ofot7-lSmTPfo'
    api_args:
      chat_id: -966329966
      parse_mode: "markdown"
      text: "The patient has not opened the fridge door since ... "
      disable_web_page_preview: true
      disable_notification: true
