---
- name: Get OpenShift Ingress configuration
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: ocp_ingress_obj

- name: Set OpenShift Ingress domain
  ansible.builtin.set_fact:
    ocp_ingress_domain: "{{ ocp_ingress_obj | json_query('resources[*].spec.domain') }}"

- name: Set OpenShift Cluster name
  ansible.builtin.set_fact:
    ocp_cluster_name: "{{ ocp_ingress_domain[0] | regex_search('^([a-z0-9-]+)\\.([a-z0-9-]+)\\.([a-z0-9-]+).(.*)$', '\\2') }}"
